// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace wfa_scolaireDepart.Models;

[Table("AUTEURS")]
public partial class Auteur
{
    [Key]
    [Column("ID_AUTEUR")]
    public int IdAuteur { get; set; }

    [Column("NOM")]
    [StringLength(50)]
    public string Nom { get; set; }

    [Column("PRENOM")]
    [StringLength(50)]
    public string Prenom { get; set; }

    [Column("DATE_NAISSANCE", TypeName = "datetime")]
    public DateTime? DateNaissance { get; set; }

    [Column("DATE_DECES", TypeName = "datetime")]
    public DateTime? DateDeces { get; set; }

    [Column("NATIONALITE")]
    [StringLength(50)]
    public string Nationalite { get; set; }

    [ForeignKey("IdAuteur")]
    [InverseProperty("IdAuteurs")]
    public virtual ICollection<Livre> IdLivres { get; set; } = new List<Livre>();
}