// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace wfa_scolaireDepart.Models;

[Table("CATEGORIES")]
public partial class Category
{
    [Key]
    [Column("ID_CATEGORIE")]
    public int IdCategorie { get; set; }

    [Column("LIB_CATEGORIE")]
    [StringLength(50)]
    public string LibCategorie { get; set; }

    [InverseProperty("IdCategorieNavigation")]
    public virtual ICollection<Livre> Livres { get; set; } = new List<Livre>();
}