// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using wfa_scolaireDepart.Models;

namespace wfa_scolaireDepart.Models
{
    public partial class Glg_bdContext
    {

        [DbFunction("SommePrixLivrePArAuteur", "dbo")]
        public IQueryable<SommePrixLivrePArAuteurResult> SommePrixLivrePArAuteur(int? id_auteur)
        {
            return FromExpression(() => SommePrixLivrePArAuteur(id_auteur));
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<SommePrixLivrePArAuteurResult>().HasNoKey();
        }
    }
}
