// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using wfa_scolaireDepart.Models;

namespace wfa_scolaireDepart.Models
{
    public partial interface IGlg_bdContextProcedures
    {
        //Task<int> AddOrUpdateStudentAsync(string no_da, string nom, string prenom, string email, OutputParameter<int?> returnValue, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetTotalCoursesResult>> GetTotalCoursesAsync(string session, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> GetTotalCoursesWithOutputAsync(string session, OutputParameter<int?> nombreDeCours, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ListerResultatEtudiantResult>> ListerResultatEtudiantAsync(string no_da, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
