// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace wfa_scolaireDepart.Models
{
    public partial class ListerResultatEtudiantResult
    {
        public string no_da { get; set; }
        [StringLength(100)]
        public string nom { get; set; }
        [StringLength(100)]
        public string prenom { get; set; }
        [Column("note", TypeName = "decimal(5,2)")]
        public decimal? note { get; set; }
        [StringLength(100)]
        public string nomCours { get; set; }
        public string no_session { get; set; }
    }
}
