// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace wfa_scolaireDepart.Models;

[Table("LIVRES")]
public partial class Livre
{
    [Key]
    [Column("ID_LIVRE")]
    public int IdLivre { get; set; }

    [Column("TITRE")]
    [StringLength(100)]
    public string Titre { get; set; }

    [Column("ISBN")]
    [StringLength(50)]
    public string Isbn { get; set; }

    [Column("RESUME")]
    [StringLength(255)]
    public string Resume { get; set; }

    [Column("ID_CATEGORIE")]
    public int? IdCategorie { get; set; }

    [Column("PRIX", TypeName = "money")]
    public decimal? Prix { get; set; }

    [ForeignKey("IdCategorie")]
    [InverseProperty("Livres")]
    public virtual Category IdCategorieNavigation { get; set; }

    [ForeignKey("IdLivre")]
    [InverseProperty("IdLivres")]
    public virtual ICollection<Auteur> IdAuteurs { get; set; } = new List<Auteur>();
}