// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace wfa_scolaireDepart.Models
{
    public partial class SommePrixLivrePArAuteurResult
    {
        public int ID_AUTEUR { get; set; }
        [StringLength(50)]
        public string NOM { get; set; }
        [StringLength(50)]
        public string PRENOM { get; set; }
        [Column("prix total", TypeName = "money")]
        public decimal? prixtotal { get; set; }
    }
}
