// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace wfa_scolaireDepart.Models;

[Table("tbl_departement")]
public partial class TblDepartement
{
    [Key]
    [Column("no_departement")]
    public int NoDepartement { get; set; }

    [Required]
    [Column("nom_departement")]
    [StringLength(30)]
    public string NomDepartement { get; set; }

    [Column("no_employe_resp")]
    [StringLength(8)]
    public string NoEmployeResp { get; set; }

    [ForeignKey("NoEmployeResp")]
    [InverseProperty("TblDepartements")]
    public virtual TblEmploye NoEmployeRespNavigation { get; set; }

    [InverseProperty("NoDepartementNavigation")]
    public virtual ICollection<TblEmploye> TblEmployes { get; set; } = new List<TblEmploye>();
}