// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace wfa_scolaireDepart.Models;

[Table("tbl_employe")]
public partial class TblEmploye
{
    [Key]
    [Column("no_employe")]
    [StringLength(8)]
    public string NoEmploye { get; set; }

    [Required]
    [Column("nom")]
    [StringLength(30)]
    public string Nom { get; set; }

    [Column("prenom")]
    [StringLength(30)]
    public string Prenom { get; set; }

    [Column("no_departement")]
    public int NoDepartement { get; set; }

    [ForeignKey("NoDepartement")]
    [InverseProperty("TblEmployes")]
    public virtual TblDepartement NoDepartementNavigation { get; set; }

    [InverseProperty("NoEmployeRespNavigation")]
    public virtual ICollection<TblDepartement> TblDepartements { get; set; } = new List<TblDepartement>();
}