// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace wfa_scolaireDepart.Models;

[PrimaryKey("NoDa", "NoOffreCours")]
[Table("tbl_inscription")]
public partial class TblInscription
{
    [Key]
    [Column("no_da")]
    [StringLength(7)]
    public string NoDa { get; set; }

    [Key]
    [Column("no_offreCours")]
    public int NoOffreCours { get; set; }

    [Column("note", TypeName = "decimal(5, 2)")]
    public decimal? Note { get; set; }

    [ForeignKey("NoDa")]
    [InverseProperty("TblInscriptions")]
    public virtual TblEtudiant NoDaNavigation { get; set; }

    [ForeignKey("NoOffreCours")]
    [InverseProperty("TblInscriptions")]
    public virtual TblOffreCour NoOffreCoursNavigation { get; set; }
}