// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace wfa_scolaireDepart.Models;

[Table("tbl_offreCours")]
[Index("NoSession", "NoCours", Name = "un_offreCours", IsUnique = true)]
public partial class TblOffreCour
{
    [Key]
    [Column("no_offreCours")]
    public int NoOffreCours { get; set; }

    [Required]
    [Column("no_session")]
    [StringLength(5)]
    public string NoSession { get; set; }

    [Required]
    [Column("no_cours")]
    [StringLength(8)]
    public string NoCours { get; set; }

    [ForeignKey("NoCours")]
    [InverseProperty("TblOffreCours")]
    public virtual TblCour NoCoursNavigation { get; set; }

    [ForeignKey("NoSession")]
    [InverseProperty("TblOffreCours")]
    public virtual TblSession NoSessionNavigation { get; set; }

    [InverseProperty("NoOffreCoursNavigation")]
    public virtual ICollection<TblInscription> TblInscriptions { get; set; } = new List<TblInscription>();
}