// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace wfa_scolaireDepart.Models;

[Table("tbl_session")]
public partial class TblSession
{
    [Key]
    [Column("no_session")]
    [StringLength(5)]
    public string NoSession { get; set; }

    [InverseProperty("NoSessionNavigation")]
    public virtual ICollection<TblOffreCour> TblOffreCours { get; set; } = new List<TblOffreCour>();
}