// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace wfa_scolaireDepart.Models;

[Keyless]
public partial class VueListerResultat
{
    [Required]
    [Column("no_da")]
    [StringLength(7)]
    public string NoDa { get; set; }

    [Required]
    [Column("nom")]
    [StringLength(100)]
    public string Nom { get; set; }

    [Required]
    [Column("prenom")]
    [StringLength(100)]
    public string Prenom { get; set; }

    [Column("note", TypeName = "decimal(5, 2)")]
    public decimal? Note { get; set; }

    [Column("no_offreCours")]
    public int NoOffreCours { get; set; }
}